host: localhost
port: 19000
cassandraHosts:
 - 127.0.0.1:19180
 - 127.0.0.1:19180
rollupKeyspace: data
#metricsWriterClass: "com.rackspacecloud.blueflood.dw.fake.FakeMetricsWriter"
metricsWriterClass: "com.rackspacecloud.blueflood.io.AstyanaxMetricsWriter"
scopingTenants:
 - CAN_SCOPE_01
 - CAN_SCOPE_02
forceNewCollectionTime: true