server:
  applicationConnectors:
    - type: http
      bindHost: 127.0.0.1
      port: 19000
  adminConnectors:
    - type: http
      bindHost: 127.0.0.1
      port: 19010
populateBluefloodConfigurationSettings: false
cassandraHosts:
 - 127.0.0.1:19180
 - 127.0.0.1:19180
rollupKeyspace: data
metricsWriterClass: "com.rackspacecloud.blueflood.io.AstyanaxMetricsWriter"
forceNewCollectionTime: true
riemann:
  enabled: false
  host: 127.0.0.1
  port: 5555
  prefix: foo
  localhost: 127.0.0.1
  tags: [zee, fee, bee]
  separator: "."
  ttl: 604800
graphite:
  enabled: false
  host: 127.0.0.1
  port: 2003